CREATE TABLE w_wpeople (
    spec_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    wFirstNameTX VARCHAR(150) NOT NULL,
    wFamilyNameTX VARCHAR(150) NOT NULL,
    wSurnameTX VARCHAR(150) NOT NULL,
    wRecordStateSY VARCHAR(100) NOT NULL,
    wPreviousStateSY VARCHAR(100) NOT NULL,
    wStatusCL VARCHAR(150) NOT NULL,
    wPreviousStatusCL VARCHAR(150) NOT NULL,
    primary key (spec_id) );
INSERT INTO s_state(wo_name, wo_state)
     VALUES ('wPeople', 'null'),
            ('wPeople', 'wDraft'),
            ('wPeople', 'wActive'),
            ('wPeople', 'wRetired');
INSERT INTO s_state_transit(
    wo_name, current_state, next_state, action_name, action_label, close_window, read_only, secondary_action)
VALUES ('wPeople', 'null', 'wDraft', 'wCreate', 'Create', FALSE, FALSE, FALSE),
       ('wPeople', 'wDraft', 'wActive','wActivate', 'Activate', FALSE, FALSE, TRUE),
       ('wPeople', 'wDraft', 'wRetired', 'wRetire', 'Retire', FALSE, FALSE, FALSE),
       ('wPeople', 'wActive', 'wRetired', 'wRetire', 'Retire', FALSE, FALSE, FALSE),
       ('wPeople', 'wActive', 'wActive', 'wActivate', 'Retire', FALSE, FALSE, FALSE),
       ('wPeople', 'wRetired', 'null', 'wDelete', 'Delete', FALSE, FALSE, FALSE);
INSERT INTO s_statetransit_subaction(
    action_name, id_state_transit, process_name)
SELECT t.action_name, t.id_state_transit, 'wPeople - Synchronous - when Create'
  FROM s_state_transit t
 WHERE t.wo_name = 'wPeople' AND t.current_state = 'null' AND t.next_state = 'wDraft' AND t.action_name = 'wCreate';
INSERT INTO s_statetransit_subact_inclusion(
    action_name, inclusion, exclusion, id_state_transit, id_statetransit_subact)
SELECT 'transitA', TRUE, FALSE, t.id_state_transit, s.id_statetransit_subact
  FROM s_state_transit t JOIN s_statetransit_subaction s ON t.id_state_transit = s.id_state_transit
WHERE t.wo_name = 'wPeople' AND t.current_state = 'null' AND t.next_state = 'wDraft' AND t.action_name = 'wCreate';
INSERT INTO s_statetransit_subact_inclusion(
    action_name, inclusion, exclusion, id_state_transit, id_statetransit_subact)
SELECT 'transitB', FALSE, TRUE, t.id_state_transit, s.id_statetransit_subact
FROM s_state_transit t JOIN s_statetransit_subaction s ON t.id_state_transit = s.id_state_transit
WHERE t.wo_name = 'wPeople' AND t.current_state = 'null' AND t.next_state = 'wDraft' AND t.action_name = 'wCreate';
INSERT INTO s_statetransit_subact_attribute(
    field_name, const_value, id_state_transit, id_statetransit_subact)
SELECT 'wStateSY', 'Draft', t.id_state_transit, s.id_statetransit_subact
  FROM s_state_transit t JOIN s_statetransit_subaction s ON t.id_state_transit = s.id_state_transit
 WHERE t.wo_name = 'wPeople' AND t.current_state = 'null' AND t.next_state = 'wDraft' AND t.action_name = 'wCreate';
INSERT INTO s_statetransit_subact_attribute(
    field_name, const_value, id_state_transit, id_statetransit_subact)
SELECT 'wPreviousStateSY', 'null', t.id_state_transit, s.id_statetransit_subact
FROM s_state_transit t JOIN s_statetransit_subaction s ON t.id_state_transit = s.id_state_transit
WHERE t.wo_name = 'wPeople' AND t.current_state = 'null' AND t.next_state = 'wDraft' AND t.action_name = 'wCreate'
